apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysinfo-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: sysinfo
        envFrom:
        - configMapRef:
            name: sysinfo-configmap
